services:
  culturebot:
    container_name: culturebot
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TOKEN=$TOKEN
      - CLIENT_ID=$CLIENT_ID
      - MYSQL_PW=$MYSQL_PW
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/

  db:
    container_name: db
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PW
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 15s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data: